# Generated by Django 3.2 on 2021-04-13 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0004_auto_20210412_1233'),
        ('access', '0002_auto_20210413_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='works.collection'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
