# Generated by Django 3.2 on 2021-04-14 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_auto_20210413_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='allow_children',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='access.accesstoken'),
        ),
    ]
