# Generated by Django 3.2 on 2021-04-14 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_auto_20210413_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='access.accesstoken'),
        ),
    ]
