# Generated by Django 3.2.4 on 2021-06-20 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20210412_1233'),
        ('access', '0006_auto_20210413_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='allow_children',
        ),
        migrations.RemoveField(
            model_name='accesstoken',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accesstoken',
            name='parent',
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='works.collection'),
        ),
    ]
