# Generated by Django 3.2 on 2021-04-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='collections',
            field=models.ManyToManyField(blank=True, null=True, to='works.Collection'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
    ]
