# Generated by Django 3.2 on 2021-04-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20210411_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='collections',
            field=models.ManyToManyField(blank=True, to='works.Collection'),
        ),
    ]
