# Generated by Django 3.2 on 2021-04-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_work_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='collections',
        ),
        migrations.AddField(
            model_name='work',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='works.collection'),
        ),
    ]
