# Generated by Django 3.2.4 on 2021-06-28 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20210412_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
